# This is a basic workflow to help you get started with Actions

name: test-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  titleText : ""

jobs:
  update_wp_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: convert2HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
      
      - name: getHTML
        id: getcontentHTML
        run: |
          text=$(cat /home/runner/work/GH2WP/GH2WP/index.html) 
          echo "::set-output name=contentHTML::$text"

      - name: makedata
        id: postData
        run: |
          #titleText = ""
          echo "hello"

      - name: post
        id: postInfo
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://swsd.net/wp-json/wp/v2/posts/155'
          method: 'POST'
          username: ${{ secrets.AWX_USER }}
          password: ${{ secrets.AWX_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"content" : ${{ steps.getcontentHTML.outputs.contentHTML }} , "status" : "pending" }'
          
      - name: Show Response
        run: |
          echo ${{ steps.postInfo.outputs.response }}
          echo ${{ steps.postInfo.outputs.headers }}
